[package]
name = "sourcers"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
capstone = "0.12.0"
capstone-sys = "0.16.0"
clap = { version = "4.5.18", features = ["derive"] }
log = "0.4.22"
